/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "sage": "rgb(var(--rgb-sage, 124 139 111) / <alpha-value>)",
        "dark-green": "#2D4A3E",
        "beige": "#F5F0EB",
        "gold": "rgb(var(--rgb-gold, 196 165 90) / <alpha-value>)",
        "dark-text": "#1A1A1A",
        "ink": "rgb(var(--rgb-ink, 23 23 23) / <alpha-value>)",
        "accent": "rgb(var(--rgb-accent, 115 115 115) / <alpha-value>)",
        "primary": "rgb(var(--rgb-primary, 22 51 40) / <alpha-value>)",
        "primary-container": "#2d4a3e",
        "secondary": "rgb(var(--rgb-secondary, 84 99 73) / <alpha-value>)",
        "secondary-container": "#d8e8c7",
        "tertiary": "#3b2c00",
        "tertiary-container": "#574100",
        "tertiary-fixed": "#ffdf96",
        "surface": "rgb(var(--rgb-surface, 254 248 243) / <alpha-value>)",
        "surface-container": "#f2ede8",
        "surface-container-low": "rgb(var(--rgb-surface-low, 248 243 238) / <alpha-value>)",
        "surface-container-high": "#ece7e2",
        "surface-container-highest": "#e6e2dd",
        "on-primary": "#ffffff",
        "on-primary-container": "#99b9a9",
        "on-secondary-container": "#5a694f",
        "on-surface": "#1d1b19",
        "on-surface-variant": "#424844",
        "on-tertiary-container": "#ceae62",
        "outline": "#727974",
        "outline-variant": "#c1c8c3",
        "error": "#ba1a1a",
      },
      fontFamily: {
        "headline": ['"DM Sans"', '"Plus Jakarta Sans"', 'sans-serif'],
        "body": ['"Inter"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
