package com.naturessence.shared.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

@Entity
@Table(name = "coupons")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Coupon {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String code;

    /** Dynamic type: pourcentage, fixe, livraison, cadeau, bogo */
    @Column(nullable = false)
    private String type;

    /** Discount value (percentage or fixed amount) */
    @Builder.Default
    private double valeur = 0;

    /** Minimum order amount to use the coupon */
    @Builder.Default
    private double montantMin = 0;

    /** Validity period */
    private LocalDate dateDebut;
    private LocalDate dateFin;
    private LocalTime heureDebut;
    private LocalTime heureFin;

    /** Dynamic status: actif, expire, brouillon, planifie */
    @Column(nullable = false)
    @Builder.Default
    private String statut = "actif";

    /** Usage tracking */
    @Builder.Default
    private int utilisations = 0;

    /** 0 = unlimited */
    @Builder.Default
    private int limiteGlobale = 0;

    /** Max uses per client, 0 = unlimited */
    @Builder.Default
    private int limiteClient = 1;

    /** Target segment name (references Segment.name) — null = all clients */
    private String segment;

    /** Comma-separated category names or IDs */
    @Column(columnDefinition = "TEXT")
    private String categories;

    /** Comma-separated product names or IDs (for future use) */
    @Column(columnDefinition = "TEXT")
    private String produits;

    /** Revenue generated by this coupon */
    @Builder.Default
    private double revenus = 0;

    /** Number of orders using this coupon */
    @Builder.Default
    private int commandes = 0;

    /** Conversion rate (%) */
    @Builder.Default
    private double conversion = 0;

    /** Whether this is an auto-triggered coupon */
    @Builder.Default
    private boolean auto = false;

    /** Auto trigger type: birthday, first_order, abandoned_cart, hesitant */
    private String autoTrigger;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
